### ISSUE TITLE
2nd Edition / Chapter 15 / route-parameters

### ISSUE THREAD

**Issue by lentesta** [PacktPublishing/React-and-React-Native---Third-Edition#1]
I think the code for App.js should look something like this, based on the breaking changes that were introduced after the book went to press:

import { createDrawerNavigator} from 'react-navigation-drawer';
import { createBottomTabNavigator } from 'react-navigation-tabs';
import { Platform } from 'react-native';

import { createStackNavigator } from 'react-navigation-stack';
import { createAppContainer } from 'react-navigation';

import Home from './Home';
import News from './News';
import Details from './Details';

const { createNavigator } = Platform.select({
    ios: { createNavigator: createBottomTabNavigator },
    android: { createNavigator: createDrawerNavigator }
});

const RootStack = createStackNavigator(
    {
      Home: { screen: Home },
      News: { screen: News },
      Details: { screen: Details }
    },
    {
      // specifies the screen that the user starts at when the app is opened.
      initialRouteName: 'Home',
    }
  );
  
  const App = createAppContainer(RootStack);
  
  export default App;

**Comment by adamboduch** [comment]
This repository is for the third edition of the book, yet to be published.
