### ISSUE TITLE
Installation instructions for React, React Native, Android Studio on Ubuntu

### ISSUE THREAD

**Issue by lentesta** [PacktPublishing/React-and-React-Native---Third-Edition#3]
The attached PDF was created to help get my team set up with this environment. We're using VMware while we're testing the code, to isolate our development environments. I think it'd be useful for readers to see how to get this up and running. You're free to use this material in any way you see fit.
[Install Instructions for React Native & Android Studio v3.pdf](https://github.com/PacktPublishing/React-and-React-Native---Third-Edition/files/3707455/Install.Instructions.for.React.Native.Android.Studio.v3.pdf)

**Comment by adamboduch** [comment]
Thanks for the pointer.
