### ISSUE TITLE
2nd Edition / Chapter 17 / navigation-indicators

### ISSUE THREAD

**Issue by lentesta** [PacktPublishing/React-and-React-Native---Third-Edition#4]
The updated code for App.js should be this:

// App.js
import First from './First';
import Second from './Second';
import Third from './Third';

// new stuff below here
const RootStack = createStackNavigator(
  {
    First: { 
      screen: props => (
      <First
        promise={new Promise(resolve => setTimeout(resolve, 1000))}
        {...props}
      />
    ) },
    Second: { 
      screen: props => (
        <Second
          promise={new Promise(resolve => setTimeout(resolve, 1000))}
          {...props}
        />
      )
     },
    Third: {
      screen: props => (
        <First
          promise={new Promise(resolve => setTimeout(resolve, 1000))}
          {...props}
        />
      )
    }
  },
  {
    // specifies the screen that the user starts at when the app is opened.
    initialRouteName: 'First',
  }
);

const App = createAppContainer(RootStack);

export default App;

**Comment by adamboduch** [comment]
This repository is for the yet to be published third edition of this book.
