### ISSUE TITLE
where is the key to start?

### ISSUE THREAD

**Issue by featuriz** [PacktPublishing/React-and-React-Native---Third-Edition#64]
You may be a good author. This book may have all the content about React.
But you failed to give the key man.

It's like purchasing a car without key.

How to start this man?

I have some knowledge in developing websites. I used to develop single page websites. I know some Javascript and jquery.

In 2nd chapter - first code, in which file I have to save this code and how to write my .html file.

Where is those information man?

And you are saying it's for beginners.

**Comment by featuriz** [comment]
Tell me the page number. Where are those information on this book.

**Comment by ArjunVarma39** [comment]
Hello @featuriz Could you please elaborate what do you mean by the word "Key" in this context?

**Comment by featuriz** [comment]
I found solution online. 
But you failed to mention in this book at 2nd chapter - first code.
How to System setup and running hello world example. like these information things. I found this online.

**Comment by ArjunVarma39** [comment]
Okay if you found the solution online should I close this issue?
